[package]
name = "twilight-sparkle"
version = "0.1.3"
authors = ["Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Read values from stdin using expressions understood by that file type"
repository = "https://github.com/hbina/tws"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
include = ["src/**/*", "Cargo.toml"]

[dependencies]
clap = "2.33.3"
serde_json = "1.0.62"

[[bin]]
name = "tws"

[profile.release]
lto = true

[lib]
name = "parsers"
path = "src/parsers/lib.rs"
