name: build and publish

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        run: cargo test --verbose

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-apple-darwin
          mkdir dist
          mkdir builds
      - name: Build Win64
        run: |
          cargo rustc --bin twilight-sparkle --release --verbose --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
          mkdir builds/twilight-sparkle-win64
          cp target/x86_64-pc-windows-gnu/release/twilight-sparkle.exe builds/twilight-sparkle-win64/twilight-sparkle-win64.exe
          tar -C builds -czvf dist/twilight-sparkle-win64.tar.gz twilight-sparkle-win64
      - name: Build Linux
        run: |
          cargo rustc --bin twilight-sparkle --release --verbose --target=x86_64-unknown-linux-gnu
          mkdir builds/twilight-sparkle-linux
          cp target/x86_64-unknown-linux-gnu/release/twilight-sparkle builds/twilight-sparkle-linux/twilight-sparkle-linux
          tar -C builds -czvf dist/twilight-sparkle-linux.tar.gz twilight-sparkle-linux
      - name: Cache Mac OS dependencies
        id: cache-macos
        uses: actions/cache@v1
        with:
          path: osxcross
          key: ${{ runner.os }}-osxcross

      - name: Install Mac OS dependencies
        if: steps.cache-macos.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          sudo tools/get_dependencies.sh
          wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX10.10.sdk.tar.xz
          mv MacOSX10.10.sdk.tar.xz tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
      - name: Build Mac OS
        run: |
          export PATH="$(pwd)/osxcross/target/bin:$PATH"
          export LIBZ_SYS_STATIC=1
          export CC="$(pwd)/osxcross/target/bin/o64-clang"
          export CXX="$(pwd)/osxcross/target/bin/o64-clang++"
          cargo
 build --bin twilight-sparkle --release --verbose --target x86_64-apple-darwin
          mkdir builds/twilight-sparkle-macos
          cp target/x86_64-apple-darwin/release/twilight-sparkle builds/twilight-sparkle-macos/twilight-sparkle-macos
          tar -C builds -czvf dist/twilight-sparkle-macos.tar.gz twilight-sparkle-macos
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/twilight-sparkle-win64.tar.gz
            dist/twilight-sparkle-linux.tar.gz
            dist/twilight-sparkle-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish npm package
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ".npmrc"
          npm publish
      - name: Publish cargo package
        env:
          CARGO_ACCESS_TOKEN: ${{ secrets.CARGO_ACCESS_TOKEN }}
        run: |
          cargo login "$CARGO_ACCESS_TOKEN"
          cargo publish
