name: build and publish

on:
  push:
    tags: ["v*.*.*", "add-github-workflows"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        run: cargo test --verbose

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          rustup +nightly target add x86_64-pc-windows-gnu
          rustup +nightly target add x86_64-unknown-linux-gnu
          rustup +nightly target add x86_64-apple-darwin
          mkdir dist
          mkdir builds
      - name: Build Win64
        run: |
          cargo +nightly rustc --bin lulu --release --verbose --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
          mkdir builds/lulu-win64
          cp target/x86_64-pc-windows-gnu/release/lulu.exe builds/lulu-win64/lulu-win64.exe
          tar -C builds -czvf dist/lulu-win64.tar.gz lulu-win64
      - name: Build Linux
        run: |
          cargo +nightly rustc --bin lulu --release --verbose --target=x86_64-unknown-linux-gnu
          mkdir builds/lulu-linux
          cp target/x86_64-unknown-linux-gnu/release/lulu builds/lulu-linux/lulu-linux
          tar -C builds -czvf dist/lulu-linux.tar.gz lulu-linux
      - name: Cache Mac OS dependencies
        id: cache-macos
        uses: actions/cache@v1
        with:
          path: osxcross
          key: ${{ runner.os }}-osxcross

      - name: Install Mac OS dependencies
        if: steps.cache-macos.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          sudo tools/get_dependencies.sh
          wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX10.10.sdk.tar.xz
          mv MacOSX10.10.sdk.tar.xz tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
      - name: Build Mac OS
        run: |
          export PATH="$(pwd)/osxcross/target/bin:$PATH"
          export LIBZ_SYS_STATIC=1
          export CC=o64-clang
          export CXX=o64-clang++
          cargo +nightly build --bin lulu --release --target x86_64-apple-darwin
          mkdir builds/lulu-macos
          cp target/x86_64-apple-darwin/release/lulu builds/lulu-macos/lulu-macos
          tar -C builds -czvf dist/lulu-macos.tar.gz lulu-macos
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/lulu-win64.tar.gz
            dist/lulu-linux.tar.gz
            dist/lulu-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish cargo package
        env:
          CARGO_ACCESS_TOKEN: ${{ secrets.CARGO_ACCESS_TOKEN }}
        run: |
          cargo login "$CARGO_ACCESS_TOKEN"
          cargo publish
