name: test

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        run: cargo test --verbose

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          rustup +nightly target add x86_64-pc-windows-gnu
          rustup +nightly target add x86_64-unknown-linux-gnu
          rustup +nightly target add x86_64-apple-darwin
          mkdir dist
          mkdir builds
      - name: Build Win64
        run: |
          cargo +nightly rustc --bin tws --release --verbose --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
          mkdir builds/tws-win64
          cp target/x86_64-pc-windows-gnu/release/tws.exe builds/tws-win64/tws-win64.exe
          tar -C builds -czvf dist/tws-win64.tar.gz tws-win64
      - name: Build Linux
        run: |
          cargo +nightly rustc --bin tws --release --verbose --target=x86_64-unknown-linux-gnu
          mkdir builds/tws-linux
          cp target/x86_64-unknown-linux-gnu/release/tws builds/tws-linux/tws-linux
          tar -C builds -czvf dist/tws-linux.tar.gz tws-linux
      - name: Cache Mac OS dependencies
        id: cache-macos
        uses: actions/cache@v1
        with:
          path: osxcross
          key: ${{ runner.os }}-osxcross

      - name: Install Mac OS dependencies
        if: steps.cache-macos.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          sudo tools/get_dependencies.sh
          wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX10.10.sdk.tar.xz
          mv MacOSX10.10.sdk.tar.xz tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
      - name: Build Mac OS
        run: |
          export PATH="$(pwd)/osxcross/target/bin:$PATH"
          export LIBZ_SYS_STATIC=1
          export CC=$(pwd)/osxcross/target/bin/o64-clang
          export CXX=$(pwd)/osxcross/target/bin/o64-clang++
          cargo +nightly build --bin tws --release --verbose --target x86_64-apple-darwin
          mkdir builds/tws-macos
          cp target/x86_64-apple-darwin/release/tws builds/tws-macos/tws-macos
          tar -C builds -czvf dist/tws-macos.tar.gz tws-macos
